server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Password
    url: jdbc:mysql://localhost:3306/naat_clients
    username: activity_client
  sql:
    init:
      mode: always

    properties:
      hibernate:
        format_sql: true
  jpa:
    hibernate:
      ddl-auto: create   
