server:
  port: 8083
spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: org.postgresql.Driver
    sql:
        init:
            mode: always
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
      

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: naat_tech
    url: jdbc:postgresql://localhost:3306/activity_records
    username: naat_tech

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    password: naat_tech
    url: jdbc:postgresql://postgres:5432/activity_records
    username: naat_tech