server:
  port: 8083
spring:
    profiles:
        active: dev
    datasource:
        #driver-class-name: org.postgresql.Driver
        driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
        init:
            mode: always
    
        properties:
            hibernate:
                format_sql: true
      

---
spring:
    config:
        activate:
            on-profile: dev
    jpa:
        hibernate:
            ddl-auto: create
    datasource:
        # password: naat_tech
        password: Password
        #url: jdbc:postgresql://localhost:3306/activity_records
        url: jdbc:mysql://localhost:3306/activity_records
        #username: naat_tech
        username: record_user

---
spring:
    config:
        activate:
            on-profile: prod
    jpa:
        hibernate:
            ddl-auto: create
    datasource:
        password: naat_tech
        url: jdbc:postgresql://postgres:5432/activity_records
        username: naat_tech