server:
    port:
        8083
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/activity_records
        username: record_user
        password: Password
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: none

